// Package metrics defines all Prometheus metrics exposed by Aitra Meter.
// Import this package to register metrics; use the exported variables to record values.
package metrics

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	// JPerToken is the primary Aitra Meter metric.
	JPerToken = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "aitra_j_per_token",
		Help: "Joules per output token for the current measurement window.",
	}, []string{"namespace", "workload", "model", "hardware", "precision", "calibration_tier", "attribution_method"})

	// ClusterJPerToken is the cluster-wide aggregate J/token.
	ClusterJPerToken = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "aitra_cluster_j_per_token",
		Help: "Cluster-wide J/token computed as sum(energy) / sum(tokens) across all active workloads.",
	}, []string{"cluster", "calibration_tier"})

	// CO2PerTokenGrams is gCO2 per output token.
	CO2PerTokenGrams = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "aitra_co2_per_token_grams",
		Help: "Grams of CO2 equivalent per output token. Derived: J/token * gCO2/kWh / 3600000.",
	}, []string{"namespace", "workload", "model", "hardware", "carbon_source"})

	// CostPerMillionTokensUSD is $/M output tokens (energy cost only).
	CostPerMillionTokensUSD = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "aitra_cost_per_million_tokens_usd",
		Help: "USD per million output tokens (energy cost only). Derived: J/token * $/kWh / 3600 * 1e6.",
	}, []string{"namespace", "workload", "model", "hardware", "cost_source"})

	// NamespaceEnergyJoulesTotal is cumulative energy per namespace.
	NamespaceEnergyJoulesTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "aitra_namespace_energy_joules_total",
		Help: "Cumulative energy consumed by a namespace in joules (raw, before PUE).",
	}, []string{"namespace", "attribution_method"})

	// NamespaceTokensTotal is cumulative output tokens per namespace.
	NamespaceTokensTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "aitra_namespace_tokens_total",
		Help: "Cumulative output tokens generated by a namespace.",
	}, []string{"namespace"})

	// ClusterPowerWattsTotal is total cluster GPU power draw.
	ClusterPowerWattsTotal = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "aitra_cluster_power_watts_total",
		Help: "Total cluster GPU power draw in watts, summed across all nodes and devices.",
	}, []string{"cluster"})

	// IdlePowerWatts is per-node idle GPU power draw.
	IdlePowerWatts = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "aitra_idle_power_watts",
		Help: "GPU power draw in watts for a node when no inference requests are running.",
	}, []string{"node"})

	// IdleTimeRatio is fraction of the last hour spent idle.
	IdleTimeRatio = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "aitra_idle_time_ratio",
		Help: "Fraction of the last hour during which the node had no active inference requests (0.0-1.0).",
	}, []string{"node"})

	// GridIntensityGCO2KWh is the current grid carbon intensity.
	GridIntensityGCO2KWh = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "aitra_grid_intensity_gco2_kwh",
		Help: "Current grid carbon intensity in gCO2/kWh for the cluster grid zone.",
	}, []string{"zone", "source"})

	// MeasurementCV is the rolling coefficient of variation.
	MeasurementCV = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "aitra_measurement_cv",
		Help: "Rolling coefficient of variation of J/token over the last N windows. >0.03 = unstable.",
	}, []string{"node", "model_name"})

	// MeasurementWindowStable is 1 if CV < threshold, 0 otherwise.
	MeasurementWindowStable = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "aitra_measurement_window_stable",
		Help: "1 if the last measurement window passed the CV gate, 0 if flagged unstable.",
	}, []string{"node", "model_name"})

	// CalibrationReferenceJPerToken is the baseline for a model+hardware combo.
	CalibrationReferenceJPerToken = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "aitra_calibration_reference_j_per_token",
		Help: "Calibration baseline J/token for this model x hardware combination.",
	}, []string{"model", "hardware", "calibration_tier"})

	// GPUEnergyJoulesTotal is cumulative raw energy from measurement agent.
	GPUEnergyJoulesTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "aitra_gpu_energy_joules_total",
		Help: "Cumulative GPU energy consumed in joules since agent start.",
	}, []string{"node", "gpu_id", "model_name", "provider"})

	// GPUPowerWatts is current GPU power draw per device.
	GPUPowerWatts = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "aitra_gpu_power_watts",
		Help: "Current GPU power draw in watts.",
	}, []string{"node", "gpu_id"})

	// TokensPerJoule is the inverse of J/token — output efficiency in the forward direction.
	TokensPerJoule = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "aitra_tokens_per_joule",
		Help: "Output tokens produced per joule. Inverse of J/token. Higher is more efficient.",
	}, []string{"namespace", "workload", "model", "hardware"})

	// GPUUtilizationEfficiency is output throughput per watt — tokens per second per watt.
	GPUUtilizationEfficiency = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "aitra_gpu_utilization_efficiency",
		Help: "Output tokens per second per GPU watt. Bridges GPU utilisation and token throughput.",
	}, []string{"namespace", "workload", "model", "hardware"})
)
